spring:
  application:
    name: discovery-ws

server:
  port: 8010

eureka:
  instance:
    hostname: localhost  # Set to the hostname or IP address of the Eureka server
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  # URL where other services can register
