spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-ws
          uri: lb://users-ws
          predicates:
            - Path=/users/status
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    register-with-eureka: true
    fetch-registry: true
